apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-dep
  labels:
    app: angular-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app 
    spec:
      containers:
      - name: angular-app
        image: athapa1/angular-app:latest 
        ports:
        - containerPort: 3000