apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  selector:
    app: react-app 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 3333 #Service port
    targetPort: 3000 #The port for the React.js application container